<a href="https://colab.research.google.com/github/dbace23/hacktiv8/blob/main/h8dsft_Linear_Algebra1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#import library needed
import numpy as np

Membuat tensor dengan python

$$ \begin{bmatrix} \begin{bmatrix} 23 & 50 \\ 7 & 12 \ \end{bmatrix} \begin{bmatrix} 57 & 67 \\ 99 & 43 \end{bmatrix} \\\\ \begin{bmatrix} 75 & 21 \\ 57 & 12 \ \end{bmatrix} \begin{bmatrix} 87 & 26 \\ 18 & 84 \end{bmatrix} \end{bmatrix} $$


In [3]:
#membuat tensor dengan python
T=np.array([[23,50,7,12],
            [57,67,99,43],
            [75,21,57,12],
            [87,26,18,84]
])
T

array([[23, 50,  7, 12],
       [57, 67, 99, 43],
       [75, 21, 57, 12],
       [87, 26, 18, 84]])

Lakukan perkalian terhadap matrix berikut:

$$ A = \begin{bmatrix} 23 & 50 & 19 \ 7 & 12 & 109 \ 57 & 67 & 98 \end{bmatrix} \begin{bmatrix} 17 \ 22 \ 19 \end{bmatrix} $$

In [4]:
#membuat tensor dengan python
A=np.array([[23,50,19],
            [7,12,109],
            [57,67,98],
            [17,22,19]
])
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98],
       [ 17,  22,  19]])

In [7]:
x =T@A
x

array([[ 1482,  2483,  6801],
       [ 8154, 11233, 18905],
       [ 5325,  8085,  9528],
       [ 4637,  7716,  7847]])

Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

$$ \begin{bmatrix} 23 & 50 & 19 \ 7 & 12 & 109 \ 57 & 67 & 98 \end{bmatrix} $$

In [8]:
#membuat tensor dengan python
B=np.array([[23,50,19],
            [7,12,109],
            [57,67,98]
])
B

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [10]:
#transpose
BT= B.T
BT

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [11]:
#determinan
from  numpy.linalg import det
np.linalg.det(BT)

131343.99999999997

In [12]:
np.linalg.inv(BT)

array([[-0.0466485 ,  0.04208034, -0.00163692],
       [-0.02761451,  0.00891552,  0.0099662 ],
       [ 0.03975819, -0.01807467, -0.00056341]])